-- MyTime V1.1 数据库迁移脚本
-- 使用方式：复制本文件全部内容到 Supabase Dashboard > SQL Editor 执行。
-- 说明：该脚本会从 Summer Sprint 单项目模型升级到 MyTime 项目制模型。

create table if not exists public.projects (
  id bigint generated by default as identity primary key,
  name text not null,
  slug text not null unique,
  password_hash text not null,
  start_date date not null,
  end_date date not null,
  total_goal text not null,
  study_start_time text not null default '19:30',
  study_end_time text not null default '23:30',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.task_boards (
  id bigint generated by default as identity primary key,
  project_id bigint not null references public.projects(id) on delete cascade,
  name text not null,
  kind text not null default 'long_term' check (kind in ('temporary', 'long_term')),
  goal text,
  is_custom boolean not null default false,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint task_boards_long_term_goal check (kind <> 'long_term' or coalesce(goal, '') <> '')
);

create table if not exists public.weekly_plan_items (
  id bigint generated by default as identity primary key,
  weekly_plan_id bigint not null references public.weekly_plans(id) on delete cascade,
  task_board_id bigint not null references public.task_boards(id) on delete cascade,
  daily_minutes integer not null default 0 check (daily_minutes >= 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (weekly_plan_id, task_board_id)
);

alter table public.weekly_plans add column if not exists project_id bigint references public.projects(id) on delete cascade;
alter table public.weekly_plans drop constraint if exists weekly_plans_week_start_date_key;
alter table public.study_sessions add column if not exists project_id bigint references public.projects(id) on delete cascade;
alter table public.study_sessions add column if not exists task_board_id bigint references public.task_boards(id) on delete set null;
alter table public.study_sessions alter column category drop not null;

-- 旧字段仍保留，避免历史结构依赖；新版本不再使用 thesis_minutes/exam_minutes/career_minutes/category。

do $$
declare
  default_project_id bigint;
  thesis_board_id bigint;
  exam_board_id bigint;
  career_board_id bigint;
  board_names text[] := array['考公','论文','秋招','科研项目','运动','阅读','学生工作','娱乐','外语','兴趣爱好'];
  board_name text;
  sort_index integer := 1;
  existing_plan record;
begin
  select id into default_project_id from public.projects where slug = 'mytime' limit 1;

  if default_project_id is null then
    insert into public.projects (
      name,
      slug,
      password_hash,
      start_date,
      end_date,
      total_goal,
      study_start_time,
      study_end_time
    ) values (
      'MyTime',
      'mytime',
      '__NEEDS_PASSWORD__',
      current_date,
      current_date + interval '180 days',
      '感知时间的流逝，每天靠近目标。',
      '19:30',
      '23:30'
    ) returning id into default_project_id;
  end if;

  foreach board_name in array board_names loop
    insert into public.task_boards (project_id, name, kind, goal, is_custom, sort_order)
    values (
      default_project_id,
      board_name,
      'long_term',
      case when board_name = '论文' then '持续推进论文相关目标' else board_name || '阶段目标' end,
      false,
      sort_index
    )
    on conflict do nothing;
    sort_index := sort_index + 1;
  end loop;

  select id into thesis_board_id from public.task_boards where project_id = default_project_id and name = '论文' limit 1;
  select id into exam_board_id from public.task_boards where project_id = default_project_id and name = '考公' limit 1;
  select id into career_board_id from public.task_boards where project_id = default_project_id and name = '秋招' limit 1;

  update public.weekly_plans set project_id = default_project_id where project_id is null;

  for existing_plan in select * from public.weekly_plans where project_id = default_project_id loop
    if thesis_board_id is not null and coalesce(existing_plan.thesis_minutes, 0) > 0 then
      insert into public.weekly_plan_items (weekly_plan_id, task_board_id, daily_minutes)
      values (existing_plan.id, thesis_board_id, existing_plan.thesis_minutes)
      on conflict (weekly_plan_id, task_board_id) do update set daily_minutes = excluded.daily_minutes;
    end if;
    if exam_board_id is not null and coalesce(existing_plan.exam_minutes, 0) > 0 then
      insert into public.weekly_plan_items (weekly_plan_id, task_board_id, daily_minutes)
      values (existing_plan.id, exam_board_id, existing_plan.exam_minutes)
      on conflict (weekly_plan_id, task_board_id) do update set daily_minutes = excluded.daily_minutes;
    end if;
    if career_board_id is not null and coalesce(existing_plan.career_minutes, 0) > 0 then
      insert into public.weekly_plan_items (weekly_plan_id, task_board_id, daily_minutes)
      values (existing_plan.id, career_board_id, existing_plan.career_minutes)
      on conflict (weekly_plan_id, task_board_id) do update set daily_minutes = excluded.daily_minutes;
    end if;
  end loop;

  update public.study_sessions
  set project_id = default_project_id
  where project_id is null;

  update public.study_sessions
  set task_board_id = case
    when category = 'thesis' then thesis_board_id
    when category = 'exam' then exam_board_id
    when category = 'career' then career_board_id
    else thesis_board_id
  end
  where task_board_id is null;
end $$;

alter table public.weekly_plans alter column project_id set not null;
alter table public.study_sessions alter column project_id set not null;
alter table public.study_sessions alter column task_board_id set not null;

create unique index if not exists idx_weekly_plans_project_week_start on public.weekly_plans (project_id, week_start_date);
create index if not exists idx_task_boards_project on public.task_boards (project_id, sort_order);
create index if not exists idx_weekly_plan_items_plan on public.weekly_plan_items (weekly_plan_id);
create index if not exists idx_study_sessions_project_date on public.study_sessions (project_id, study_date desc);

create or replace function public.set_updated_at()
returns trigger as $$
begin
  new.updated_at = now();
  return new;
end;
$$ language plpgsql;

drop trigger if exists set_projects_updated_at on public.projects;
create trigger set_projects_updated_at
before update on public.projects
for each row execute function public.set_updated_at();

drop trigger if exists set_task_boards_updated_at on public.task_boards;
create trigger set_task_boards_updated_at
before update on public.task_boards
for each row execute function public.set_updated_at();

drop trigger if exists set_weekly_plan_items_updated_at on public.weekly_plan_items;
create trigger set_weekly_plan_items_updated_at
before update on public.weekly_plan_items
for each row execute function public.set_updated_at();
