-- Summer Sprint V1.0 Supabase 数据库初始化脚本
-- 使用方式：复制本文件内容到 Supabase Dashboard > SQL Editor 执行。

create table if not exists public.app_settings (
  id integer primary key default 1,
  study_start_time text not null default '19:30',
  study_end_time text not null default '23:30',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint app_settings_single_row check (id = 1)
);

create table if not exists public.weekly_plans (
  id bigint generated by default as identity primary key,
  week_start_date date not null unique,
  week_end_date date not null,
  theme text not null default '学习推进周',
  thesis_minutes integer not null default 0 check (thesis_minutes >= 0),
  exam_minutes integer not null default 0 check (exam_minutes >= 0),
  career_minutes integer not null default 0 check (career_minutes >= 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.study_sessions (
  id bigint generated by default as identity primary key,
  study_date date not null,
  start_time timestamptz not null,
  end_time timestamptz not null,
  duration_minutes integer not null check (duration_minutes > 0),
  category text not null check (category in ('thesis', 'exam', 'career')),
  content text not null default '',
  created_at timestamptz not null default now()
);

create index if not exists idx_weekly_plans_week_start on public.weekly_plans (week_start_date desc);
create index if not exists idx_study_sessions_study_date on public.study_sessions (study_date desc);
create index if not exists idx_study_sessions_created_at on public.study_sessions (created_at desc);

create or replace function public.set_updated_at()
returns trigger as $$
begin
  new.updated_at = now();
  return new;
end;
$$ language plpgsql;

drop trigger if exists set_app_settings_updated_at on public.app_settings;
create trigger set_app_settings_updated_at
before update on public.app_settings
for each row execute function public.set_updated_at();

drop trigger if exists set_weekly_plans_updated_at on public.weekly_plans;
create trigger set_weekly_plans_updated_at
before update on public.weekly_plans
for each row execute function public.set_updated_at();

insert into public.app_settings (id, study_start_time, study_end_time)
values (1, '19:30', '23:30')
on conflict (id) do update set
  study_start_time = excluded.study_start_time,
  study_end_time = excluded.study_end_time;

-- 初始化 2026-07-13 至 2026-07-19 的“论文冲刺周”。
-- 如果上线时已经不是这一周，可以在网页里的“配置”中重新保存本周计划。
insert into public.weekly_plans (week_start_date, week_end_date, theme, thesis_minutes, exam_minutes, career_minutes)
values ('2026-07-13', '2026-07-19', '论文冲刺周', 180, 60, 0)
on conflict (week_start_date) do update set
  week_end_date = excluded.week_end_date,
  theme = excluded.theme,
  thesis_minutes = excluded.thesis_minutes,
  exam_minutes = excluded.exam_minutes,
  career_minutes = excluded.career_minutes;

-- V1.0 由 Next.js 服务端使用 service role key 访问数据库，前端不会直接暴露 Supabase key。
-- 如需进一步强化，可在 Supabase 中保持 RLS 开启，并仅允许 service role 访问。
